@baseURLSessionService = http://127.0.0.1:3001/API
@baseURLReportService = http://127.0.0.1:3003/API

@baseURLOrganizationService = http://127.0.0.1:3002/API


# @name login
POST {{baseURLSessionService}}/user/login
content-type: application/json

{
    "email":"byron@xyz.com",
    "password":"root123"
}

###

# @name login
POST {{baseURLSessionService}}/user/login
content-type: application/json

{
    "email":"byron@reporter.com",
    "password":"123456"
}

###

# @name login
POST {{baseURLSessionService}}/user/login
content-type: application/json

{
    "email":"byron@organization.com",
    "password":"123456"
}

###

@authToken = {{login.response.body.token}}

POST {{baseURLSessionService}}/user/register
content-type: application/json

{
    "email":"byron@hotmail.com",
    "password":"123456",
    "username":"byronman"
}

###

POST {{baseURLSessionService}}/user/register
content-type: application/json

{
    "email":"byron@organization.com",
    "password":"123456",
    "username":"byronman"
}

###

POST {{baseURLSessionService}}/user/set-role
content-type: application/json

{
    "email":"byron@hotmail.com",
    "role":2,    
}

###

GET {{baseURLSessionService}}/user/logout
content-type: application/json
Authorization: bearer {{authToken}}

###

GET {{baseURLSessionService}}/user/all/0
content-type: application/json
Authorization: bearer {{authToken}}

#######################################################################################

POST {{baseURLReportService}}/report/add
content-type: application/json
Authorization: bearer {{authToken}}

{
    "level":0,
    "text":"warning ---PO--Dog",
    "geo":{ "lat":"-0.937195", "lon":"-78.603299"},
    "situation":"animal"
}

####

GET {{baseURLReportService}}/report/near/-78.603299/-0.937195
content-type: application/json
Authorization: bearer {{authToken}}


###

GET {{baseURLReportService}}/report/list-all/2021-05-10/2021-05-11
content-type: application/json
Authorization: bearer {{authToken}}

###

POST {{baseURLOrganizationService}}/organization/attend-notification/:id
content-type: application/json
Authorization: bearer {{authToken}}

###

POST {{baseURLOrganizationService}}/organization/cancel-attention/:id
content-type: application/json
Authorization: bearer {{authToken}}

###

GET {{baseURLOrganizationService}}/organization/attentions
content-type: application/json
Authorization: bearer {{authToken}}

###

DELETE http://127.0.0.1:3003/API/report/cancel/hpa:notifications:1621032311237-0
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjEwMzAzOTMsImV4cCI6MTYyMTExNjc5MywiYXVkIjoiaGVjdG9yQGguY29tIiwiaXNzIjoiMTI3LjAuMC4xIn0.Dlcw-AMxJ3cnAK8HxI5N8DM3zXOHMhuemThAZoJW7EQ